version: 0
metadata:
  name: "taskcluster-docs"
  description: "Automation for taskcluster-docs"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - pull_request.opened
          - pull_request.reopened
          - pull_request.synchronize
    payload:
      maxRunTime: 3600
      image: "node:5.11"
      command:
        - "/bin/bash"
        - "--login"
        - "-c"
        - "git clone $GITHUB_BASE_REPO_URL && cd taskcluster-docs && git fetch origin pull/$GITHUB_PULL_REQUEST/head:pull-request && git checkout pull-request && bash taskcluster-build.sh pull-request"
    metadata:
      name: "taskcluster-docs check"
      description: "Run `gulp check` to verify docs well-formedness`"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - push
        branches:
          - master
          - publish-test
    payload:
      maxRunTime: 3600
      image: "node:5.11"
      command:
        - "/bin/bash"
        - "--login"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd taskcluster-docs && git checkout $GITHUB_HEAD_BRANCH && bash taskcluster-build.sh push"
    metadata:
      name: "taskcluster-docs publish"
      description: "Run `gulp publish` to publish the docs to S3`"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
