safe: true
lsi: false
pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data

exclude:
  - 'README.md'
  - 'Gemfile'
  - 'CNAME'

# We can only have two levels of menu, this **** is hardcoded into the menu in
# the template. Entries have the following properties:
#  * `name`, link display name,
#  * `url`, URL for the page relative to root, must equal `page.url`,
#  * `href`, optional overrides `url`, used when linking to an `index.html` page
#    and  you don't want the URL to feature `index.html`. But `url` property
#   still needs to match `page.url` to set active tags correctly.
sections:
  - name: Introduction
    url:  /index.html
    href: /
    links:
      - name: Github Projects
        url:  https://github.com/taskcluster
  - name: Queue
    url:  /queue/index.html
    href: /queue/
    links:
    - name: API Documentation
      url:  /queue/api-docs/index.html
      href: /queue/api-docs/
    - name: AMQP Exchanges
      url:  /queue/exchanges/index.html
      href: /queue/exchanges/
    - name: Queue Web Interface
      url:  http://queue.taskcluster.net
    - name: Source Repository
      url:  https://github.com/taskcluster/taskcluster-queue
  - name: Scheduler
    url:  /scheduler/index.html
    href: /scheduler/
    links:
    - name: API Documentation
      url:  /scheduler/api-docs/index.html
      href: /scheduler/api-docs/
    - name: AMQP Exchanges
      url:  /scheduler/events/index.html
      href: /scheduler/events/
    - name: Source Repository
      url:  https://github.com/taskcluster/task-graph-scheduler
  - name: Services
    url:  /services/index.html
    href: /services/
    links:
      - name: AWS Provisioner
        url:  /services/aws-provisioner/index.html
        href: /services/aws-provisioner/
      - name: Task Indexing
        url:  /services/index/index.html
        href: /services/index/
  - name: Auth
    url:  /auth/index.html
    href: /auth/
    links:
      - name: Restricting Scopes
        url:  /auth/authorized-scopes/index.html
        href: /auth/authorized-scopes/
      - name: Temporary Credentials
        url:  /auth/temporary-credentials/index.html
        href: /auth/temporary-credentials/
      - name: Signed Urls
        url:  /auth/signed-urls/index.html
        href: /auth/signed-urls/
      - name: API Documentation
        url:  /auth/api-docs/index.html
        href: /auth/api-docs/
      - name: Authentication Manager
        url:  https://tools.taskcluster.net/auth/
      - name: Source Repository
        url:  https://github.com/taskcluster/taskcluster-auth
  - name: Docker Worker
    url:  /docker-worker/index.html
    href: /docker-worker/
  - name: Tools
    url:  /tools/index.html
    href: /tools/
    links:
      - name: Task Inspector
        url:  /tools/task-inspector/index.html
        href: /tools/task-inspector/
      - name: Task-Graph Inspector
        url:  /tools/task-graph-inspector/index.html
        href: /tools/task-graph-inspector/
      - name: Task Creator
        url:  /tools/task-creator/index.html
        href: /tools/task-creator/
      - name: Reference Formats
        url:  /tools/references/index.html
        href: /tools/references/
