safe: true
lsi: false
highlighter: rouge
kramdown:
  input: GFM

exclude:
  - 'README.md'
  - 'Gemfile'
  - 'CNAME'
  - 'node_modules'

# We can only have two levels of menu, this **** is hardcoded into the menu in
# the template. Entries have the following properties:
#  * `name`, link display name,
#  * `url`, URL for the page relative to root, must equal `page.url`,
#  * `href`, optional overrides `url`, used when linking to an `index.html` page
#    and  you don't want the URL to feature `index.html`. But `url` property
#   still needs to match `page.url` to set active tags correctly.
sections:
  - name: About
    links:
    - name: Introduction
      url:  /index.html
      href: /
    - name: Getting Started
      url:  /introduction/getting-started/index.html
      href: /introduction/getting-started/
    - name: Core Principles
      url:  /introduction/principles/index.html
      href: /introduction/principles/
    - name: Blog
      url:  http://planet.mozilla.org/taskcluster
  - name: Learn
    links:
    - name: Introduction
      url:  /learn/index.html
      href: /learn/
    - divider: true
    - heading: Tutorials
    - name: Introduction
      url:  /learn/tutorials/index.html
      href: /learn/tutorials
    - name: Modern Async Javascript
      url:  /learn/async-javascript/index.html
      href: /learn/async-javascript
    - name: Authenticate
      url:  /learn/authenticate/index.html
      href: /learn/authenticate
    - name: Create a Task
      url:  /learn/create-task/index.html
      href: /learn/create-task
    - divider: true
    - heading: Presentations
    - name: Screencasts
      url: /presentations/index.html
      href: /presentations/
    - name: TaskCluster Introduction
      url:  /presentations/intro/index.html
      href: /presentations/intro/
    - name: TaskCluster Scopes
      url:  /presentations/scopes/index.html
      href: /presentations/scopes/
    - name: "TaskCluster 101: Platform Introduction"
      url:  /presentations/TC-101/index.html
      href: /presentations/TC-101/
    - name: "TaskCluster 102: Advanced TaskCluster User Issues"
      url:  /presentations/TC-102/index.html
      href: /presentations/TC-102/
      # name: Listening for Task Events (PulseListener + WebListener)
      # name: Tasks w. Custom Routes (custom routes, scopes, WebListener)
      # name: Browsing the Index
      # name: Indexing Tasks
      # name: Create a Task-Graph

      # name: Docker in docker-worker
      # name:
  - name: Manual
    links:
    - heading: Queue
    - name: Overview
      url:  /queue/index.html
      href: /queue/
    - name: Worker Interaction
      url:  /queue/worker-interaction/index.html
      href: /queue/worker-interaction/
    - divider: true
    - heading: Scheduler
    - name: Overview
      url:  /scheduler/index.html
      href: /scheduler/
    - divider: true
    - heading: Authentication
    - name: Overview
      url:  /auth/index.html
      href: /auth/
    - name: Scopes
      url:  /auth/scopes/index.html
      href: /auth/scopes/
    - name: Clients
      url:  /auth/clients/index.html
      href: /auth/clients/
    - name: Roles
      url:  /auth/roles/index.html
      href: /auth/roles/
    - name: Restricting Scopes
      url:  /auth/authorized-scopes/index.html
      href: /auth/authorized-scopes/
    - name: Temporary Credentials
      url:  /auth/temporary-credentials/index.html
      href: /auth/temporary-credentials/
    - name: Signed Urls
      url:  /auth/signed-urls/index.html
      href: /auth/signed-urls/
    - divider: true
    - heading: Workers
    - name: Overview
      url:  /workers/index.html
      href: /workers/
    - name: TaskCluster Worker
      url:  /workers/taskcluster-worker/index.html
      href: /workers/taskcluster-worker/
    - name: Docker Worker
      url:  /workers/docker-worker/index.html
      href: /workers/docker-worker/
    - name: Generic Worker
      url:  /workers/generic-worker/index.html
      href: /workers/generic-worker/
    - divider: true
    - heading: Tools
    - name: Web Tools
      url:  /tools/web/index.html
      href: /tools/web/
    - name: Client Libraries
      url:  /tools/clients/index.html
      href: /tools/clients/
    - name: Reference Formats
      url:  /tools/references/index.html
      href: /tools/references/
    - divider: true
    - heading: Miscellaneous
    - name: AWS Provisioner
      url:  /aws-provisioner/index.html
      href: /aws-provisioner/
    - name: GitHub
      url:  /services/core/github/index.html
      href: /services/core/github/
    - divider: true
    - heading: Development
    - name: Conventions
      url:  /devel/conventions/index.html
      href: /devel/conventions/
    - name: Namespaces
      url:  /devel/namespaces/index.html
      href: /devel/namespaces/
    - name: Github Projects
      url:  https://github.com/taskcluster
    - name: Travis CI Status
      url:  https://travis-ci.org/taskcluster
    - name: Open Github Issues/PRs
      url:  https://github.com/search?utf8=%E2%9C%93&q=user%3Ataskcluster+is%3Aopen&type=Issues&ref=searchresults
  - name: Services
    links:
    - divider: true
    - heading: TaskCluster Platform
    - name: Authentication - API Documentation
      url:  /services/platform/auth/api-docs/index.html
      href: /services/platform/auth/api-docs/
    - name: Queue - API Documentation
      url:  /services/platform/queue/api-docs/index.html
      href: /services/platform/queue/api-docs/
    - name: Queue - AMQP Exchanges
      url:  /services/platform/queue/exchanges/index.html
      href: /services/platform/queue/exchanges/
    - name: Scheduler - API Documentation
      url:  /services/platform/scheduler/api-docs/index.html
      href: /services/platform/scheduler/api-docs/
    - name: Scheduler - AMQP Exchanges
      url:  /services/platform/scheduler/exchanges/index.html
      href: /services/platform/scheduler/exchanges/
    - divider: true
    - heading: TaskCluster Core Services
    - name: AWS Provisioner - API Documentation
      url:  /services/core/aws-provisioner/api-docs/index.html
      href: /services/core/aws-provisioner/api-docs/
    - name: AWS Provisioner - AMQP Exchanges
      url:  /services/core/aws-provisioner/exchanges/index.html
      href: /services/core/aws-provisioner/exchanges/
    - name: Index - API Documentation
      url:  /services/core/index/api-docs/index.html
      href: /services/core/index/api-docs/
    - name: Purge-Cache - API Documentation
      url:  /services/core/purge-cache/api-docs/index.html
      href: /services/core/purge-cache/api-docs/
    - name: GitHub - API Documentation
      url:  /services/core/github/api-docs/index.html
      href: /services/core/github/api-docs/
    - name: GitHub - AMQP Exchanges
      url:  /services/core/github/exchanges/index.html
      href: /services/core/github/exchanges/
    - name: Secrets - API Documentation
      url:  /services/core/secrets/api-docs/index.html
      href: /services/core/secrets/api-docs/
    - name: Hooks - API Documentation
      url:  /services/core/hooks/api-docs/index.html
      href: /services/core/hooks/api-docs/
    - name: Cors-Proxy - Interface Documentation
      url:  /services/core/cors-proxy/index.html
      href: /services/core/cors-proxy/
