safe: true
lsi: false
highlighter: rouge
kramdown:
  input: GFM

exclude:
  - 'README.md'
  - 'Gemfile'
  - 'CNAME'
  - 'node_modules'

# We can only have two levels of menu, this **** is hardcoded into the menu in
# the template. Entries have the following properties:
#  * `name`, link display name,
#  * `url`, URL for the page relative to root, must equal `page.url`,
#  * `href`, optional overrides `url`, used when linking to an `index.html` page
#    and  you don't want the URL to feature `index.html`. But `url` property
#   still needs to match `page.url` to set active tags correctly.
sections:
  - name: About
    links:
    - name: Introduction
      url:  /index.html
      href: /
    - name: Getting Started
      url:  /introduction/getting-started/index.html
      href: /introduction/getting-started/
    - name: Blog
      url:  http://planet.mozilla.org/taskcluster
  - name: Learn More
    links:
    - name: Introduction
      url:  /learn/index.html
      href: /learn/
    - divider: true
    - heading: Tutorials
    - name: Introduction
      url:  /learn/tutorials/index.html
      href: /learn/tutorials
    - name: Modern Async Javascript
      url:  /learn/async-javascript/index.html
      href: /learn/async-javascript
    - name: Authenticate
      url:  /learn/authenticate/index.html
      href: /learn/authenticate
    - name: Create a Task
      url:  /learn/create-task/index.html
      href: /learn/create-task
    - divider: true
    - title: Presentations
      url: /presentations/index.html
      href: /presentations/
  - name: Manual
    links:
    - heading: Working with Tasks
    - name: Queue
      url:  /manual/tasks/queue/index.html
      href: /manual/tasks/queue/
    - name: Worker-Queue Interaction
      url:  /manual/tasks/worker-interaction/index.html
      href: /manual/tasks/worker-interaction/
    - name: Scheduler
      url:  /manual/tasks/scheduler/index.html
      href: /manual/tasks/scheduler/
    - heading: Using TaskCluster APIs
    - name: Authentication
      url:  /manual/apis/index.html
      href: /manual/apis/
    - name: Scopes
      url:  /manual/apis/scopes/index.html
      href: /manual/apis/scopes/
    - name: Clients
      url:  /manual/apis/clients/index.html
      href: /manual/apis/clients/
    - name: Roles
      url:  /manual/apis/roles/index.html
      href: /manual/apis/roles/
    - name: Restricting Scopes
      url:  /manual/apis/authorized-scopes/index.html
      href: /manual/apis/authorized-scopes/
    - name: Temporary Credentials
      url:  /manual/apis/temporary-credentials/index.html
      href: /manual/apis/temporary-credentials/
    - name: Signed Urls
      url:  /manual/apis/signed-urls/index.html
      href: /manual/apis/signed-urls/
    - divider: true
    - heading: Version Control Interfaces
      # TC-VCS
    - name: GitHub
      url:  /manual/vcs/github/index.html
      href: /manual/vcs/github/
      # Mozilla-TC
      # Gaia-TC
    - divider: true
    - heading: Task Execution
    - name: AWS Provisioner
      url:  /manual/execution/aws-provisioner/index.html
      href: /manual/execution/aws-provisioner/
    - name: Workers
      url:  /manual/execution/workers/index.html
      href: /manual/execution/workers/
    - name: TaskCluster Worker
      url:  /manual/execution/workers/taskcluster-worker/index.html
      href: /manual/execution/workers/taskcluster-worker/
    - name: Docker Worker
      url:  /manual/execution/workers/docker-worker/index.html
      href: /manual/execution/workers/docker-worker/
    - name: Generic Worker
      url:  /manual/execution/workers/generic-worker/index.html
      href: /manual/execution/workers/generic-worker/
    - divider: true
    - heading: Tools
    - name: Web Tools
      url:  /manual/tools/web/index.html
      href: /manual/tools/web/
    - name: Client Libraries
      url:  /manual/tools/clients/index.html
      href: /manual/tools/clients/
    - name: Reference Formats
      url:  /manual/tools/references/index.html
      href: /manual/tools/references/
    - divider: true
    - heading: Developing TaskCluster
    - name: Core Principles
      url:  /manual/devel/principles/index.html
      href: /manual/devel/principles/
    - name: Conventions
      url:  /manual/devel/conventions/index.html
      href: /manual/devel/conventions/
    - name: Namespaces
      url:  /manual/devel/namespaces/index.html
      href: /manual/devel/namespaces/
    - name: Github Projects
      url:  https://github.com/taskcluster
    - name: Travis CI Status
      url:  https://travis-ci.org/taskcluster
    - name: Open Github Issues/PRs
      url:  https://github.com/search?utf8=%E2%9C%93&q=user%3Ataskcluster+is%3Aopen&type=Issues&ref=searchresults
  - name: Services
    links:
    - divider: true
    - heading: TaskCluster Platform
    - name: Authentication - API Documentation
      url:  /services/platform/auth/api-docs/index.html
      href: /services/platform/auth/api-docs/
    - name: Queue - API Documentation
      url:  /services/platform/queue/api-docs/index.html
      href: /services/platform/queue/api-docs/
    - name: Queue - AMQP Exchanges
      url:  /services/platform/queue/exchanges/index.html
      href: /services/platform/queue/exchanges/
    - name: Scheduler - API Documentation
      url:  /services/platform/scheduler/api-docs/index.html
      href: /services/platform/scheduler/api-docs/
    - name: Scheduler - AMQP Exchanges
      url:  /services/platform/scheduler/exchanges/index.html
      href: /services/platform/scheduler/exchanges/
    - divider: true
    - heading: TaskCluster Core Services
    - name: AWS Provisioner - API Documentation
      url:  /services/core/aws-provisioner/api-docs/index.html
      href: /services/core/aws-provisioner/api-docs/
    - name: AWS Provisioner - AMQP Exchanges
      url:  /services/core/aws-provisioner/exchanges/index.html
      href: /services/core/aws-provisioner/exchanges/
    - name: Index - API Documentation
      url:  /services/core/index/api-docs/index.html
      href: /services/core/index/api-docs/
    - name: Purge-Cache - API Documentation
      url:  /services/core/purge-cache/api-docs/index.html
      href: /services/core/purge-cache/api-docs/
    - name: GitHub - API Documentation
      url:  /services/core/github/api-docs/index.html
      href: /services/core/github/api-docs/
    - name: GitHub - AMQP Exchanges
      url:  /services/core/github/exchanges/index.html
      href: /services/core/github/exchanges/
    - name: Secrets - API Documentation
      url:  /services/core/secrets/api-docs/index.html
      href: /services/core/secrets/api-docs/
    - name: Hooks - API Documentation
      url:  /services/core/hooks/api-docs/index.html
      href: /services/core/hooks/api-docs/
    - name: Cors-Proxy - Interface Documentation
      url:  /services/core/cors-proxy/index.html
      href: /services/core/cors-proxy/
