safe: true
lsi: false
pygments: true
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data

exclude:
  - 'README.md'
  - 'Gemfile'
  - 'CNAME'

# We can only have two levels of menu, this **** is hardcoded into the menu in
# the template. Entries have the following properties:
#  * `name`, link display name,
#  * `url`, URL for the page relative to root, must equal `page.url`,
#  * `href`, optional overrides `url`, used when linking to an `index.html` page
#    and  you don't want the URL to feature `index.html`. But `url` property
#   still needs to match `page.url` to set active tags correctly.
sections:
  - name: Introduction
    url:  /index.html
    href: /
    links:
      - name: Github Projects
        url:  https://github.com/taskcluster
  - name: Queue
    url:  /queue/index.html
    href: /queue/
    links:
    - name: API Documentation
      url:  /queue/api-docs.html
    - name: AMQP Exchanges
      url:  /queue/events.html
    - name: Task Storage
      url:  /queue/task-storage.html
    - name: Queue Web Interface
      url:  http://queue.taskcluster.net
    - name: Source Repository
      url:  https://github.com/taskcluster/taskcluster-queue
  - name: Provisioners
    url:  /provisioners/index.html
    href: /provisioners/
    links:
      - name: AWS Provisioners
        url:  /provisioners/aws-provisioner.html
  - name: Tools
    url:  /tools/index.html
    href: /tools/
    links:
      - name: Task Inspector
        url:  /tools/task-inspector/index.html
        href: /tools/task-inspector/
      - name: Task Creator
        url:  /tools/task-creator/index.html
        href: /tools/task-creator/